service: thundra-demo-localstack

plugins:
  - serverless-deployment-bucket
  - serverless-localstack # only activated when stage is "local"

custom:
  stage: ${opt:stage, "local"}
  region: ${opt:region, "us-east-1"}
  deploymentBucketName: ${self:service}-deployment-bucket-${self:custom.stage}
  tableName: ${self:service}-app-requests
  bucketName: ${self:service}-archive-bucket
  queueName: ${self:service}-request-queue
  topicName: ${self:service}-request-topic
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    debug: true
    autostart: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  memorySize: ${opt:memory, 512}
  timeout: ${opt:timeout, 60}
  deploymentBucket:
    name: ${self:custom.deploymentBucketName}
  environment:
    APP_REQUESTS_TABLE_NAME: ${self:custom.tableName}
    REQUEST_QUEUE_URL:
      Ref: requestQueue
    REQUEST_TOPIC_ARN:
      Ref: requestTopic
    ARCHIVE_BUCKET_NAME: ${self:custom.bucketName}
    THUNDRA_APIKEY: ${env:THUNDRA_APIKEY}
    THUNDRA_AGENT_REPORT_REST_BASEURL: ${env:THUNDRA_AGENT_REPORT_REST_BASEURL}
    THUNDRA_AGENT_TRACE_INSTRUMENT_TRACEABLECONFIG: ${env:THUNDRA_AGENT_TRACE_INSTRUMENT_TRACEABLECONFIG}

package:
  excludeDevDependencies: true
  patterns:
    - '!.npmrc'
    - '!Makefile'

functions:
  http_handleRequest:
    handler: ./src/handler/app-handler.handler
    events:
      - http:
          path: /request/{requestId}
          method: get
      - http:
          path: /requests
          method: post
  backend_processRequest:
    handler: ./src/handler/processing-handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [requestQueue, Arn]
  backend_archiveResult:
    handler: ./src/handler/archive-handler.handler
    events:
      - sns:
          arn:
            Fn::GetAtt: [requestTopic, Arn]
          topicName: ${self:custom.topicName}
    environment:
      THUNDRA_AGENT_TRACE_SPAN_LISTENERCONFIG: ${env:THUNDRA_DYNAMODB_CHAOS}

resources:
  Resources:
    appDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: requestId
            AttributeType: S
        KeySchema:
          - AttributeName: requestId
            KeyType: HASH
    archiveBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    requestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
        VisibilityTimeout: 60
    requestTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}